name: Build
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        run: |
          git clone --recursive https://github.com/opa334/TrollStore.git
          cd TrollStore
          
          export THEOS=~/theos
          git clone --recursive https://github.com/theos/theos.git $THEOS
          
          mkdir -p $THEOS/sdks
          cd $THEOS/sdks
          git clone --depth 1 https://github.com/theos/sdks.git
          cp -r sdks/iPhoneOS16.5.sdk .
          rm -rf sdks
          
          cd $GITHUB_WORKSPACE/TrollStore/RootHelper
          make clean
          make FINALPACKAGE=1
          
          cp .theos/obj/RootHelper ../TrollHelper/Resources/
          
          cd ../TrollHelper
          make clean
          make FINALPACKAGE=1
          
          mkdir -p $GITHUB_WORKSPACE/output
          cp .theos/obj/TrollHelper $GITHUB_WORKSPACE/output/
          cp ../RootHelper/.theos/obj/RootHelper $GITHUB_WORKSPACE/output/
          
      - uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: output/*
