name: 生成签名证书

on:
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
      - run: pip3 install cryptography
      - run: python3 make_cert.py "0000000000" "./cert_output" "troll"
      - uses: actions/upload-artifact@v4
        with:
          name: certificates
          path: cert_output/
          retention-days: 90
